<?php

/**
 * @file
 * Contains fkm.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fkm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fkm module.
    case 'help.page.fkm':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A custom module for FilmyKhabar.com.') . '</p>';
      return $output;

    default:
  }
}
