<?php

/**
 * @file
 * Contains migrate_filmykhabar.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_filmykhabar_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_filmykhabar module.
    case 'help.page.migrate_filmykhabar':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate data from old FilmyKhabar custom CMS to Drupal 8.') . '</p>';
      return $output;

    default:
  }
}
