<?php

/**
 * @file
 * Contains filmykhabar_migration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function filmykhabar_migration_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
      // Main module help for the filmykhabar_migration module.
    case 'help.page.filmykhabar_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate data from old FilmyKhabar custom CMS to Drupal 8.') . '</p>';
      return $output;

    default:
  }
}
